# Generated by Django 5.2.1 on 2025-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_admin', 'Branch Admin')], max_length=50, unique=True),
        ),
    ]
