# Generated by Django 5.1.6 on 2025-04-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_price_asset_status_asset_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='vendor',
        ),
    ]
