# Generated by Django 5.1.6 on 2025-04-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_remove_asset_price_remove_asset_status_and_more'),
        ('vendor', '0002_alter_vendor_contact_person_alter_vendor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance'), ('BROKEN', 'Broken'), ('ASSIGNED', 'Assigned')], default='AVAILABLE', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
    ]
