# Generated by Django 5.1.6 on 2025-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_price_asset_status_asset_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
