# Generated by Django 5.1.6 on 2025-03-23 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_quantity_alter_asset_image_and_more'),
        ('assetitem', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
