# Generated by Django 5.1.6 on 2025-03-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetitem', '0002_remove_assetitem_quantity_alter_assetitem_asset_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
