# Generated by Django 5.1.6 on 2025-03-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetitem', '0003_alter_assetitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
