# Generated by Django 5.1.6 on 2025-04-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetitem', '0004_alter_assetitem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance'), ('BROKEN', 'Broken'), ('NOT AVAILABLE', 'Not Available'), ('ASSIGNED', 'Assigned')], default='AVAILABLE', max_length=50),
        ),
    ]
