# Generated by Django 5.1.6 on 2025-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetitem', '0005_alter_assetitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
